MCM: false
MCQ: false
MCQMLM: false
MLM: false
MSM: false
MSMMLM: false
al: 1.0
alpha: 0.9
batch_size: 64
beta: 0.999
bias_lr_factor: 2.0
cmm_loss_weight: 1.0
cmt_depth: 4
dataset_name: CUHK-PEDES
distributed: false
eval_period: 1
focal_three_fusion_loss: false
focal_three_fusion_loss2: false
focal_three_fusion_loss3: false
focal_three_fusion_loss4: false
focal_three_fusion_loss5: false
focal_three_fusion_loss6: false
focalthree_four_fusion_loss: false
focalthree_fusion_loss: false
four_fusion_loss: false
fusion_way: add
ga: 2.0
gamma: 0.1
id_loss_weight: 1.0
img_aug: false
img_size: !!python/tuple
- 384
- 128
klp: 1.0
label_mix: false
learnable_loss_weight: false
local_rank: 0
log_period: 100
loss_names: itc
lr: 1.0e-05
lr_factor: 5.0
lrscheduler: step
masked_token_rate: 0.8
masked_token_unchanged_rate: 0.1
mcm_loss_weight: 1.0
mcq_loss_weight: 1.0
milestones: !!python/tuple
- 20
- 50
mlm_loss_weight: 1.0
momentum: 0.9
name: baseline
nlp_aug: false
num_colors: 60
num_epoch: 60
num_instance: 4
num_workers: 8
only_fusion_loss: false
only_sketch: false
only_text: false
optimizer: Adam
output_dir: /data1/ccq/multimodality\CUHK-PEDES\20240926_211338_baseline
pa: 0.1
power: 0.9
pretrain_choice: ViT-B/16
resume: false
resume_ckpt_file: ''
root_dir: /data0/data_ccq/CUHK-PEDES/
sampler: random
stride_size: 16
target_lr: 1.0e-08
temperature: 0.07
test_batch_size: 512
test_setting: 0
text_length: 77
training: true
use_imageid: false
val_dataset: test
vocab_size: 49408
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0
